### ISSUE TITLE
JDAT-1220: Regions Support

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#518]
Ability to draw fractional pixel regions of various shapes that can be exported as Astropy `regions`.

- [x] Circles
- [ ] Ellipses
  - ~From UI/UX doc: "Circles are not separate than ellipse, (and rectangles not separate from squares) to get a perfect circle or square press shift to constrain the proportions"~ Deferred to #624
  - ~Currently not possible, see glue-viz/glue-jupyter#223~ Deferred to #635
- [x] Rectangles
- [ ] ~Slit-shaped regions (esp. NIRSpec MSA) -- What does this really mean? Like a rotated rectangle? PO says yes.~ Deferred to #634
  - Currently not possible, see glue-viz/glue-jupyter#224
  - Acceptable workaround: Plugin for user to control the rotation angle of individual ellipse or rectangle.

UI/UX: https://www.stsci.edu/~jkotler/Imviz/#id=xvaaay&p=region_subset_workflow&g=1

1. Menu to select various shapes (as in existing `jdaviz` viewers)
  - [x] Button for Circles
  - [x] Button for Rectangles
2. ~Integrate subsets pulldown with region selection (see mockup).~  Shouldn't have to "Create new" to make a new region. Clicking and dragging with region tool selected creates new region and adds it to the list of subsets.
  - [x] ~Integrate subsets pulldown with region selection (need Mario's help)~ MOVED to #608
  - [ ] ~Shouldn't have to "Create new" to make a new region~ Deferred to #633 
    - Erik Tollerud says there is a "mode" to do this already somewhere. We agreed that this "mode" should be documented but not made the default because having to remove an accidentally drawn shape is worse than having to click "create new" to draw new shape. Something like `specviz.app.get_viewer('spectrum-viewer').toolbar_active_subset.selected = []`
    - @pllim unable to find a sane way to accomplish this and needs SME to help. See glue-viz/glue#2192
    - If this won't be the default behavior anyway, is there much value in cramming this into MVP?
  - [x] Clicking and dragging 

OUT OF SCOPE: Getting slit info for an instrument from header, and so on. This issue only covers hand-drawn slits.

https://jira.stsci.edu/browse/JDAT-1220

**Comment by eteq** [comment]
After some discussion, I'm now thinking that " Integrate subsets pulldown with region selection" is better done as a separate issue, since it's a much bigger project than the other parts of this.

**Comment by eteq** [comment]
Oh and to clarify a bit more on the "Create new" item: the current behavior is that if you make a new selection it creates a region the first time, but after that it "moves" the region.  That bullet point (I think originating from @orifox ?) was to instead make it create a new region every time.  @pllim and I discussed out-of-band that we think the current behavior is still what we want as default. But there is value in an *optional* mode where instead of glue changing the current subset/region to the one newly created, it *stays* in "create new" mode.  We can discuss later if we really want that to be default for imviz.

**Comment by astrofrog** [comment]
The place where the behavior is controlled is in the ``EditSubsetMode`` class - to create a subset every time one would need to do: https://github.com/glue-viz/glue/pull/2192 - of course we shouldn't merge that PR, but just to point out where the code needs to be changed. Maybe we could make it a (in glue) non-default option to have this behavior, and potentially have a way to toggle that option from the jdaviz UI. Here's what it looks like with that change:

![Peek 2021-05-13 16-39](https://user-images.githubusercontent.com/314716/118149814-d2d7de80-b409-11eb-8c81-cda0b515f51f.gif)

In the above, as long as Create New is selected, it stays on that. If the user selects to edit a certain subset, it will stick to the editing mode.

**Comment by eteq** [comment]
After some out-of-band discussion, I think we've settled on the idea that the initial implementation should be:

* A panel that handles rotation angle and pixel-level centering.  That makes the workload for the rectangle easier since no UI changes are needed.  We can consider a fancy rotation thingie later if it seems like it's useful, but not in this issue.
* That panel can later also do things like altering the region properties, etc.  It should probably be a jdaviz plugin to start with, but it might/should be baked into glupyter at some point, and we can decide then whether we want to keep it as a "plugin" or not.

**Comment by eteq** [comment]
Oh and re: https://github.com/spacetelescope/jdaviz/issues/518#issuecomment-840646810 - I think that's the right behavior for the "create new" item, but not on "drag" of an existing region - rather it should be when the user lets up on the mouse button  and draws a new region. 

If the "drag" process currently has to do that when it's in the create new mode, I can live with that as a temporary measure, but we should make an issue to fix that at some point since I think to a user it's pretty unintuitive for clicking and dragging to create a bunch of new regions.

**Comment by pllim** [comment]
> pretty unintuitive for clicking and dragging to create a bunch of new regions

Perhaps, but would be very convenient to clone a bunch of shapes to make this possible:

![download](https://user-images.githubusercontent.com/2090236/118709487-05f3e680-b7eb-11eb-8c32-4032206e171e.png)

**Comment by pllim** [comment]
At the standup today, @duytnguyendtn and I have agreed to break this into smaller tickets. I will update the issue above and "archive" this when this is done. FYI.
